# Discord Bot & mySQL DB
version: '3.4'
services:
  discordbot:
    image: bwadaz/discordbot:latest
    container_name: DiscordBot
    network_mode: host
    environment:
      - DISCORD_TOKEN=<DISCORD_TOKEN>
      - CLIENT_ID=<CLIENT_ID>
      - GUILD_ID=<GUILD_ID>
      - BRADS_DISCORD_USER_ID=<BRADS_DISCORD_USER_ID>
      - PLEX_USERS_ROLE_ID=<BRADS_DISCORD_USER_ID>
    restart: unless-stopped